repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 24.10.0   # ← use the latest Black release
    hooks:
      - id: black
        language_version: python3.10   # or python3.10, python3.12 etc.

  - repo: local
    hooks:
      - id: ni-python-styleguide-lint
        name: NI Python Styleguide Lint (nps lint)
        entry: poetry run ni-python-styleguide lint
        language: system
        types: [python]
        pass_filenames: false

      - id: ni-python-styleguide-format
        name: NI Python Styleguide Format (nps format)
        entry: poetry run ni-python-styleguide format
        language: system
        types: [python]
        pass_filenames: false
