"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MessageRequest(google.protobuf.message.Message):
    """The request containing the message."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    message: builtins.str
    count: builtins.int
    def __init__(
        self,
        *,
        message: builtins.str = ...,
        count: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["count", b"count", "message", b"message"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MessageRequest: typing_extensions.TypeAlias = MessageRequest

@typing.final
class MessageResponse(google.protobuf.message.Message):
    """The response containing the reply."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPLY_FIELD_NUMBER: builtins.int
    reply: builtins.str
    def __init__(
        self,
        *,
        reply: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["reply", b"reply"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MessageResponse: typing_extensions.TypeAlias = MessageResponse
