"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
from . import message_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(
    collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta
): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class MessageStub:
    """The message service definition."""

    @typing.overload
    def __new__(cls, channel: grpc.Channel) -> MessageStub: ...
    @typing.overload
    def __new__(cls, channel: grpc.aio.Channel) -> MessageAsyncStub: ...
    SendMessage: grpc.UnaryStreamMultiCallable[
        message_pb2.MessageRequest, message_pb2.MessageResponse
    ]
    """Send message"""

@typing.type_check_only
class MessageAsyncStub(MessageStub):
    """The message service definition."""

    def __init__(self, channel: grpc.aio.Channel) -> None: ...
    SendMessage: grpc.aio.UnaryStreamMultiCallable[message_pb2.MessageRequest, message_pb2.MessageResponse]  # type: ignore[assignment]
    """Send message"""

class MessageServicer(metaclass=abc.ABCMeta):
    """The message service definition."""

    @abc.abstractmethod
    def SendMessage(
        self,
        request: message_pb2.MessageRequest,
        context: _ServicerContext,
    ) -> typing.Union[
        collections.abc.Iterator[message_pb2.MessageResponse],
        collections.abc.AsyncIterator[message_pb2.MessageResponse],
    ]:
        """Send message"""

def add_MessageServicer_to_server(
    servicer: MessageServicer, server: typing.Union[grpc.Server, grpc.aio.Server]
) -> None: ...
