[tool.poetry]
name = "assignment_10"
version = "1.0.0"
description = "Custom CLI command"
authors = ["vel"]
package-mode = true
packages = [{ include = "src"}]

[tool.poetry.dependencies]
python = "==3.10.11"
grpcio = "^1.76.0"
grpcio-tools = "^1.76.0"
mypy-protobuf = "^4.0.0"
types-protobuf = "^6.32.1.20251210"
grpc-stubs = "^1.53.0.6"
build = "^1.4.0"
click = "^8.3.1"

[tool.poetry.scripts]
echo-message = "src.task_1:echo_message"
echo-message-parallel = "src.task_2:echo_message"
emit-message = "src.task_4:repeat_message"
start-server = "src.task_3.message_server:start_server"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
